#!/usr/bin/env python3.8

import sys
import os
import time
import random

def get_word():
    words = ['Apple','Bike','Python', 'Module', 'Variable', 'Syntax']
    return  random.choice(words).upper()

def vowel_count(word):
    vowels = ['A', 'E', 'I','O','U']
    vowelCount = 0
    for vowel in vowels:
        if vowel in word:
            vowelCount += 1
    print('There are '+str(vowelCount)+' vowel(s) in the word')

def word_count(word):
    wordCount = 0
    for letter in word:
        wordCount+= 1
    print('There are '+str(wordCount)+' letters in the word')


def find_indices(word, guess):
    #ToDo look up enumeration & list comprehension 
    return [n for n, c in enumerate(word) if c == guess]


def logic(word):
    turns = len(word)+1
    alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    ass_lst = ['*'] * len(word)
    word_solved = False
    
    while turns >0:
        guess =input('Guess a letter:').upper() 
        #turns -= 1
        failed = 0
        if len(guess) >1 or guess not in alphabet:
            print('Please enter one letter at a time')
         

        if guess in ass_lst:
            print('You already guessed '+str(guess)+'! Please guess again')
            turns -= 1
            print('You have '+str(turns)+' guesses left')
            print('\n')

        elif guess in word:
            print ('Letter ' +str(guess) +' is in the word')
            for index in find_indices(word, guess):
                ass_lst[index] = guess
            print(ass_lst)
            print('You have '+str(turns)+' guesses left'+'\n')
        

        else:
            print ('Letter ' +str(guess) +' is not in the word')
            turns -= 1
            print(ass_lst)
            print('You have '+str(turns)+' guesses left'+'\n')

        if '*' not in ass_lst:
            word_solved=True
            print('Congratulations! You have won!')
            break

        elif turns == 0:
            print('Out of guesses!')
            hailmary = input('Try to guess the word: ').upper()
            if hailmary == word:
                print('Congratulations! You guessed it')
            else:
                print('The word was: ' +word) 
                break 

def play_again():
    playagain = input ('\nWould you like to play again? (y/n)').upper()
    if playagain == 'Y' or playagain == 'YES':
        main()
    else:
        exit_game()

def welcome():
    print('\n'+'*******Welcome to Guessman*******')
    time.sleep(1)
    print('******Selecting a word now******')
    print('********************************')
    print('*Game is Ready! Start guessing!*')
    print('\n')
    time.sleep(1)

def exit_game():
    print('\n'+'Thank you for playing!')

def main():    
    welcome()
    word = get_word()
    word_count(word)
    vowel_count(word)
    logic(word)
    play_again()


if __name__ == '__main__':
    main()

