#!/usr/bin/env python3.8

import sys
import os
import time
import random

def get_word():
    words = ['Apple','Bike','Python', 'Module', 'Variable']
    return  random.choice(words).upper()


def vowel_count(word):
    vowels = ['A', 'E', 'I','O','U']
    vowelCount = 0
    for vowel in vowels:
        if vowel in word:
            vowelCount += 1
    print('There are '+str(vowelCount)+' vowels in the word')

def find_indices(word, guess):
    #ToDo look up enumerate 
    #ToDo look up list comprehension 
    return [n for n, c in enumerate(word) if c == guess]


def logic():
    turns = 0
    ass_lst = ['*'] * len(word)
    word_solved = False
    while turns < len(word)+3 and not '*' in word:
        guess =input('Guess a letter:').upper() 
        turns += 1
        failed = 0
        if guess in word:
            print ('Letter ' +str(guess) +' is in the word')
            for index in find_indices(word, guess):
                ass_lst[index] = guess
            print(ass_lst) 
            
        else:
            print ('Letter ' +str(guess) +' is not in the word')
            print(ass_lst)

    if '*' not in word:
        word_solved=True
        print('Congratulations! You have won!')
        playagain()
            #turns -=1
            #print('You have '+str(turns)+' guesses left')
 

def playagain():
    play_again = input('Would you like to try again? [Yes/No] ').upper()
    if play_again == 'TRUE':
        main()
    if play_again == 'NO':
        print('Thank you for playing!')

def main():
    numGuesses = 0
    guesses = []

print('Welcome to Hangman')
time.sleep(1)
print('Picking a word now')
word = get_word()
vowel_count(word)
print('Start guessing')
time.sleep(0.5)
print('*'*len(word))

logic()

#print('You are out of guesses!')
#print('The word was ' +str(word))
