#!/usr/bin/env python3.8

import sys
import os
import time
import random

def get_word():
    words = ['Apple','Bike','Python', 'Module', 'Variable']
    return  random.choice(words).upper()


def vowel_count(word):
    vowels = ['A', 'E', 'I','O','U']
    vowelCount = 0
    for vowel in vowels:
        if vowel in word:
            vowelCount += 1
    print('There are '+str(vowelCount)+' vowels in the word')


def logic():
    turns = 0
    while turns < 10:
        guess =input('Guess a letter:')
        guess = guess.upper()
        turns += 1
        failed = 0
        for guess in word:
            if guess in word:
                print(guess)
        else:
            print("_")
            failed += 0


def main():
    numGuesses = 0
    guesses = []

print('Welcome to Hangman')
time.sleep(1)
print('Picking a word now')
word = get_word()
vowel_count(word)
print('Start guessing')
time.sleep(0.5)

logic()

