#!/usr/bin/env python3.7

import sys
import os
import time
import random


words = ['Apple','Bike','Python', 'Module', 'Variable'] 
word = random.choice(words)
vowelCount = 0
guesses = ' '
turns = 10

print('Welcome to Hangman')
time.sleep(1)

print('Picking a word now') 

vowels = ['a', 'e', 'i','o','u']
for char in word:
    if char in vowels:
        vowelCount += 1
        print('There are '+str(vowelCount)+' vowels in the word')

print('Start guessing')
time.sleep(0.5)


guess =input('Guess a letter:')

while turns > 0:
    failed = 0
    for char in word:
        if char in guess:
            print(char)
            return
        else:
            print("_")
            failed +=1
        
    if failed == 0: 
        print('You are victorious!')

    if guess not in word:
        turns -=1
        print('Letter ' +str(guess)+  ' is not in the word')
        print('You have '+str(turns)+ ' more guesses')
        
    if turns ==0:
        print("Try again next time!")
    

if __name__ == '__main__':
    while play_hangman():
        print()
